name: .NET Publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: PushNuget
      run: dotnet nuget push OpenSky.FlightLogXML/bin/Debug/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.PUBLISH_NUGET}} --skip-duplicate
      
